/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InformasiRouteImport } from './routes/informasi'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as AbsenTokenRouteImport } from './routes/absen.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAsetRouteImport } from './routes/_authenticated/admin/aset'
import { Route as AuthenticatedAdminAtmRouteImport } from './routes/_authenticated/admin/atm'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminCrmRouteImport } from './routes/_authenticated/admin/crm'
import { Route as AuthenticatedAdminEdcRouteImport } from './routes/_authenticated/admin/edc'
import { Route as AuthenticatedAdminFotoRouteImport } from './routes/_authenticated/admin/foto'
import { Route as AuthenticatedAdminIpRouteImport } from './routes/_authenticated/admin/ip'
import { Route as AuthenticatedAdminPegawaiRouteImport } from './routes/_authenticated/admin/pegawai'
import { Route as AuthenticatedAdminTiketRouteImport } from './routes/_authenticated/admin/tiket'
import { Route as AuthenticatedAdminToolsRouteImport } from './routes/_authenticated/admin/tools'
import { Route as AuthenticatedAdminTutorialRouteImport } from './routes/_authenticated/admin/tutorial'
import { Route as AuthenticatedAdminUkerRouteImport } from './routes/_authenticated/admin/uker'
import { Route as AuthenticatedAdminEventIndexRouteImport } from './routes/_authenticated/admin/event/index'
import { Route as AuthenticatedAdminEventIdRouteImport } from './routes/_authenticated/admin/event/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiRoute = InformasiRouteImport.update({
  id: '/informasi',
  path: '/informasi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const AbsenTokenRoute = AbsenTokenRouteImport.update({
  id: '/absen/$token',
  path: '/absen/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAsetRoute = AuthenticatedAdminAsetRouteImport.update({
  id: '/admin/aset',
  path: '/admin/aset',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAtmRoute = AuthenticatedAdminAtmRouteImport.update({
  id: '/admin/atm',
  path: '/admin/atm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCrmRoute = AuthenticatedAdminCrmRouteImport.update({
  id: '/admin/crm',
  path: '/admin/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminEdcRoute = AuthenticatedAdminEdcRouteImport.update({
  id: '/admin/edc',
  path: '/admin/edc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminFotoRoute = AuthenticatedAdminFotoRouteImport.update({
  id: '/admin/foto',
  path: '/admin/foto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIpRoute = AuthenticatedAdminIpRouteImport.update({
  id: '/admin/ip',
  path: '/admin/ip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPegawaiRoute =
  AuthenticatedAdminPegawaiRouteImport.update({
    id: '/admin/pegawai',
    path: '/admin/pegawai',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTiketRoute = AuthenticatedAdminTiketRouteImport.update({
  id: '/admin/tiket',
  path: '/admin/tiket',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminToolsRoute = AuthenticatedAdminToolsRouteImport.update({
  id: '/admin/tools',
  path: '/admin/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTutorialRoute =
  AuthenticatedAdminTutorialRouteImport.update({
    id: '/admin/tutorial',
    path: '/admin/tutorial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUkerRoute = AuthenticatedAdminUkerRouteImport.update({
  id: '/admin/uker',
  path: '/admin/uker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminEventIndexRoute =
  AuthenticatedAdminEventIndexRouteImport.update({
    id: '/admin/event/',
    path: '/admin/event/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEventIdRoute =
  AuthenticatedAdminEventIdRouteImport.update({
    id: '/admin/event/$id',
    path: '/admin/event/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/informasi': typeof InformasiRoute
  '/profil': typeof ProfilRoute
  '/absen/$token': typeof AbsenTokenRoute
  '/admin/aset': typeof AuthenticatedAdminAsetRoute
  '/admin/atm': typeof AuthenticatedAdminAtmRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/edc': typeof AuthenticatedAdminEdcRoute
  '/admin/foto': typeof AuthenticatedAdminFotoRoute
  '/admin/ip': typeof AuthenticatedAdminIpRoute
  '/admin/pegawai': typeof AuthenticatedAdminPegawaiRoute
  '/admin/tiket': typeof AuthenticatedAdminTiketRoute
  '/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/admin/tutorial': typeof AuthenticatedAdminTutorialRoute
  '/admin/uker': typeof AuthenticatedAdminUkerRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/event/$id': typeof AuthenticatedAdminEventIdRoute
  '/admin/event/': typeof AuthenticatedAdminEventIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/informasi': typeof InformasiRoute
  '/profil': typeof ProfilRoute
  '/absen/$token': typeof AbsenTokenRoute
  '/admin/aset': typeof AuthenticatedAdminAsetRoute
  '/admin/atm': typeof AuthenticatedAdminAtmRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/edc': typeof AuthenticatedAdminEdcRoute
  '/admin/foto': typeof AuthenticatedAdminFotoRoute
  '/admin/ip': typeof AuthenticatedAdminIpRoute
  '/admin/pegawai': typeof AuthenticatedAdminPegawaiRoute
  '/admin/tiket': typeof AuthenticatedAdminTiketRoute
  '/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/admin/tutorial': typeof AuthenticatedAdminTutorialRoute
  '/admin/uker': typeof AuthenticatedAdminUkerRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/event/$id': typeof AuthenticatedAdminEventIdRoute
  '/admin/event': typeof AuthenticatedAdminEventIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/informasi': typeof InformasiRoute
  '/profil': typeof ProfilRoute
  '/absen/$token': typeof AbsenTokenRoute
  '/_authenticated/admin/aset': typeof AuthenticatedAdminAsetRoute
  '/_authenticated/admin/atm': typeof AuthenticatedAdminAtmRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/_authenticated/admin/edc': typeof AuthenticatedAdminEdcRoute
  '/_authenticated/admin/foto': typeof AuthenticatedAdminFotoRoute
  '/_authenticated/admin/ip': typeof AuthenticatedAdminIpRoute
  '/_authenticated/admin/pegawai': typeof AuthenticatedAdminPegawaiRoute
  '/_authenticated/admin/tiket': typeof AuthenticatedAdminTiketRoute
  '/_authenticated/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/_authenticated/admin/tutorial': typeof AuthenticatedAdminTutorialRoute
  '/_authenticated/admin/uker': typeof AuthenticatedAdminUkerRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/event/$id': typeof AuthenticatedAdminEventIdRoute
  '/_authenticated/admin/event/': typeof AuthenticatedAdminEventIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/informasi'
    | '/profil'
    | '/absen/$token'
    | '/admin/aset'
    | '/admin/atm'
    | '/admin/audit'
    | '/admin/crm'
    | '/admin/edc'
    | '/admin/foto'
    | '/admin/ip'
    | '/admin/pegawai'
    | '/admin/tiket'
    | '/admin/tools'
    | '/admin/tutorial'
    | '/admin/uker'
    | '/admin/'
    | '/admin/event/$id'
    | '/admin/event/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/informasi'
    | '/profil'
    | '/absen/$token'
    | '/admin/aset'
    | '/admin/atm'
    | '/admin/audit'
    | '/admin/crm'
    | '/admin/edc'
    | '/admin/foto'
    | '/admin/ip'
    | '/admin/pegawai'
    | '/admin/tiket'
    | '/admin/tools'
    | '/admin/tutorial'
    | '/admin/uker'
    | '/admin'
    | '/admin/event/$id'
    | '/admin/event'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/informasi'
    | '/profil'
    | '/absen/$token'
    | '/_authenticated/admin/aset'
    | '/_authenticated/admin/atm'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/crm'
    | '/_authenticated/admin/edc'
    | '/_authenticated/admin/foto'
    | '/_authenticated/admin/ip'
    | '/_authenticated/admin/pegawai'
    | '/_authenticated/admin/tiket'
    | '/_authenticated/admin/tools'
    | '/_authenticated/admin/tutorial'
    | '/_authenticated/admin/uker'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/event/$id'
    | '/_authenticated/admin/event/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InformasiRoute: typeof InformasiRoute
  ProfilRoute: typeof ProfilRoute
  AbsenTokenRoute: typeof AbsenTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi': {
      id: '/informasi'
      path: '/informasi'
      fullPath: '/informasi'
      preLoaderRoute: typeof InformasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/absen/$token': {
      id: '/absen/$token'
      path: '/absen/$token'
      fullPath: '/absen/$token'
      preLoaderRoute: typeof AbsenTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/aset': {
      id: '/_authenticated/admin/aset'
      path: '/admin/aset'
      fullPath: '/admin/aset'
      preLoaderRoute: typeof AuthenticatedAdminAsetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/atm': {
      id: '/_authenticated/admin/atm'
      path: '/admin/atm'
      fullPath: '/admin/atm'
      preLoaderRoute: typeof AuthenticatedAdminAtmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/crm': {
      id: '/_authenticated/admin/crm'
      path: '/admin/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AuthenticatedAdminCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/edc': {
      id: '/_authenticated/admin/edc'
      path: '/admin/edc'
      fullPath: '/admin/edc'
      preLoaderRoute: typeof AuthenticatedAdminEdcRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/foto': {
      id: '/_authenticated/admin/foto'
      path: '/admin/foto'
      fullPath: '/admin/foto'
      preLoaderRoute: typeof AuthenticatedAdminFotoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ip': {
      id: '/_authenticated/admin/ip'
      path: '/admin/ip'
      fullPath: '/admin/ip'
      preLoaderRoute: typeof AuthenticatedAdminIpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pegawai': {
      id: '/_authenticated/admin/pegawai'
      path: '/admin/pegawai'
      fullPath: '/admin/pegawai'
      preLoaderRoute: typeof AuthenticatedAdminPegawaiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tiket': {
      id: '/_authenticated/admin/tiket'
      path: '/admin/tiket'
      fullPath: '/admin/tiket'
      preLoaderRoute: typeof AuthenticatedAdminTiketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tools': {
      id: '/_authenticated/admin/tools'
      path: '/admin/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AuthenticatedAdminToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tutorial': {
      id: '/_authenticated/admin/tutorial'
      path: '/admin/tutorial'
      fullPath: '/admin/tutorial'
      preLoaderRoute: typeof AuthenticatedAdminTutorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/uker': {
      id: '/_authenticated/admin/uker'
      path: '/admin/uker'
      fullPath: '/admin/uker'
      preLoaderRoute: typeof AuthenticatedAdminUkerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/event/': {
      id: '/_authenticated/admin/event/'
      path: '/admin/event'
      fullPath: '/admin/event/'
      preLoaderRoute: typeof AuthenticatedAdminEventIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/event/$id': {
      id: '/_authenticated/admin/event/$id'
      path: '/admin/event/$id'
      fullPath: '/admin/event/$id'
      preLoaderRoute: typeof AuthenticatedAdminEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAsetRoute: typeof AuthenticatedAdminAsetRoute
  AuthenticatedAdminAtmRoute: typeof AuthenticatedAdminAtmRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCrmRoute: typeof AuthenticatedAdminCrmRoute
  AuthenticatedAdminEdcRoute: typeof AuthenticatedAdminEdcRoute
  AuthenticatedAdminFotoRoute: typeof AuthenticatedAdminFotoRoute
  AuthenticatedAdminIpRoute: typeof AuthenticatedAdminIpRoute
  AuthenticatedAdminPegawaiRoute: typeof AuthenticatedAdminPegawaiRoute
  AuthenticatedAdminTiketRoute: typeof AuthenticatedAdminTiketRoute
  AuthenticatedAdminToolsRoute: typeof AuthenticatedAdminToolsRoute
  AuthenticatedAdminTutorialRoute: typeof AuthenticatedAdminTutorialRoute
  AuthenticatedAdminUkerRoute: typeof AuthenticatedAdminUkerRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEventIdRoute: typeof AuthenticatedAdminEventIdRoute
  AuthenticatedAdminEventIndexRoute: typeof AuthenticatedAdminEventIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAsetRoute: AuthenticatedAdminAsetRoute,
  AuthenticatedAdminAtmRoute: AuthenticatedAdminAtmRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminCrmRoute: AuthenticatedAdminCrmRoute,
  AuthenticatedAdminEdcRoute: AuthenticatedAdminEdcRoute,
  AuthenticatedAdminFotoRoute: AuthenticatedAdminFotoRoute,
  AuthenticatedAdminIpRoute: AuthenticatedAdminIpRoute,
  AuthenticatedAdminPegawaiRoute: AuthenticatedAdminPegawaiRoute,
  AuthenticatedAdminTiketRoute: AuthenticatedAdminTiketRoute,
  AuthenticatedAdminToolsRoute: AuthenticatedAdminToolsRoute,
  AuthenticatedAdminTutorialRoute: AuthenticatedAdminTutorialRoute,
  AuthenticatedAdminUkerRoute: AuthenticatedAdminUkerRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminEventIdRoute: AuthenticatedAdminEventIdRoute,
  AuthenticatedAdminEventIndexRoute: AuthenticatedAdminEventIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InformasiRoute: InformasiRoute,
  ProfilRoute: ProfilRoute,
  AbsenTokenRoute: AbsenTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
