/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InformasiRouteImport } from './routes/informasi'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as AbsenTokenRouteImport } from './routes/absen.$token'
import { Route as DetailKeyRouteImport } from './routes/detail.$key'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as ProjectIdRouteImport } from './routes/project.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAksesRouteImport } from './routes/_authenticated/admin/akses'
import { Route as AuthenticatedAdminApprovalRouteImport } from './routes/_authenticated/admin/approval'
import { Route as AuthenticatedAdminAtmRouteImport } from './routes/_authenticated/admin/atm'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminCrmRouteImport } from './routes/_authenticated/admin/crm'
import { Route as AuthenticatedAdminDriveRouteImport } from './routes/_authenticated/admin/drive'
import { Route as AuthenticatedAdminEdcRouteImport } from './routes/_authenticated/admin/edc'
import { Route as AuthenticatedAdminFotoRouteImport } from './routes/_authenticated/admin/foto'
import { Route as AuthenticatedAdminIpRouteImport } from './routes/_authenticated/admin/ip'
import { Route as AuthenticatedAdminJabatanRouteImport } from './routes/_authenticated/admin/jabatan'
import { Route as AuthenticatedAdminJenisPerangkatRouteImport } from './routes/_authenticated/admin/jenis-perangkat'
import { Route as AuthenticatedAdminPegawaiRouteImport } from './routes/_authenticated/admin/pegawai'
import { Route as AuthenticatedAdminPerangkatRouteImport } from './routes/_authenticated/admin/perangkat'
import { Route as AuthenticatedAdminPluginRouteImport } from './routes/_authenticated/admin/plugin'
import { Route as AuthenticatedAdminProjectRouteImport } from './routes/_authenticated/admin/project'
import { Route as AuthenticatedAdminProjectProgressRouteImport } from './routes/_authenticated/admin/project-progress'
import { Route as AuthenticatedAdminTiketRouteImport } from './routes/_authenticated/admin/tiket'
import { Route as AuthenticatedAdminToolsRouteImport } from './routes/_authenticated/admin/tools'
import { Route as AuthenticatedAdminTutorialRouteImport } from './routes/_authenticated/admin/tutorial'
import { Route as AuthenticatedAdminUkerRouteImport } from './routes/_authenticated/admin/uker'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminEventIndexRouteImport } from './routes/_authenticated/admin/event/index'
import { Route as AuthenticatedAdminEventIdRouteImport } from './routes/_authenticated/admin/event/$id'
import { Route as ApiPublicCompanionDeleteEventRouteImport } from './routes/api/public/companion/delete-event'
import { Route as ApiPublicCompanionDriveStatusRouteImport } from './routes/api/public/companion/drive-status'
import { Route as ApiPublicCompanionFinalizeRouteImport } from './routes/api/public/companion/finalize'
import { Route as ApiPublicCompanionUploadRouteImport } from './routes/api/public/companion/upload'
import { Route as ApiPublicCompanionUploadUrlRouteImport } from './routes/api/public/companion/upload-url'
import { Route as ApiPublicGoogleDriveCallbackRouteImport } from './routes/api/public/google-drive/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiRoute = InformasiRouteImport.update({
  id: '/informasi',
  path: '/informasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const AbsenTokenRoute = AbsenTokenRouteImport.update({
  id: '/absen/$token',
  path: '/absen/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailKeyRoute = DetailKeyRouteImport.update({
  id: '/detail/$key',
  path: '/detail/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAksesRoute = AuthenticatedAdminAksesRouteImport.update({
  id: '/admin/akses',
  path: '/admin/akses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminApprovalRoute =
  AuthenticatedAdminApprovalRouteImport.update({
    id: '/admin/approval',
    path: '/admin/approval',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAtmRoute = AuthenticatedAdminAtmRouteImport.update({
  id: '/admin/atm',
  path: '/admin/atm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCrmRoute = AuthenticatedAdminCrmRouteImport.update({
  id: '/admin/crm',
  path: '/admin/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDriveRoute = AuthenticatedAdminDriveRouteImport.update({
  id: '/admin/drive',
  path: '/admin/drive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminEdcRoute = AuthenticatedAdminEdcRouteImport.update({
  id: '/admin/edc',
  path: '/admin/edc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminFotoRoute = AuthenticatedAdminFotoRouteImport.update({
  id: '/admin/foto',
  path: '/admin/foto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIpRoute = AuthenticatedAdminIpRouteImport.update({
  id: '/admin/ip',
  path: '/admin/ip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminJabatanRoute =
  AuthenticatedAdminJabatanRouteImport.update({
    id: '/admin/jabatan',
    path: '/admin/jabatan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminJenisPerangkatRoute =
  AuthenticatedAdminJenisPerangkatRouteImport.update({
    id: '/admin/jenis-perangkat',
    path: '/admin/jenis-perangkat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPegawaiRoute =
  AuthenticatedAdminPegawaiRouteImport.update({
    id: '/admin/pegawai',
    path: '/admin/pegawai',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPerangkatRoute =
  AuthenticatedAdminPerangkatRouteImport.update({
    id: '/admin/perangkat',
    path: '/admin/perangkat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPluginRoute =
  AuthenticatedAdminPluginRouteImport.update({
    id: '/admin/plugin',
    path: '/admin/plugin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProjectRoute =
  AuthenticatedAdminProjectRouteImport.update({
    id: '/admin/project',
    path: '/admin/project',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProjectProgressRoute =
  AuthenticatedAdminProjectProgressRouteImport.update({
    id: '/admin/project-progress',
    path: '/admin/project-progress',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTiketRoute = AuthenticatedAdminTiketRouteImport.update({
  id: '/admin/tiket',
  path: '/admin/tiket',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminToolsRoute = AuthenticatedAdminToolsRouteImport.update({
  id: '/admin/tools',
  path: '/admin/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTutorialRoute =
  AuthenticatedAdminTutorialRouteImport.update({
    id: '/admin/tutorial',
    path: '/admin/tutorial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUkerRoute = AuthenticatedAdminUkerRouteImport.update({
  id: '/admin/uker',
  path: '/admin/uker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminEventIndexRoute =
  AuthenticatedAdminEventIndexRouteImport.update({
    id: '/admin/event/',
    path: '/admin/event/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEventIdRoute =
  AuthenticatedAdminEventIdRouteImport.update({
    id: '/admin/event/$id',
    path: '/admin/event/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCompanionDeleteEventRoute =
  ApiPublicCompanionDeleteEventRouteImport.update({
    id: '/api/public/companion/delete-event',
    path: '/api/public/companion/delete-event',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCompanionDriveStatusRoute =
  ApiPublicCompanionDriveStatusRouteImport.update({
    id: '/api/public/companion/drive-status',
    path: '/api/public/companion/drive-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCompanionFinalizeRoute =
  ApiPublicCompanionFinalizeRouteImport.update({
    id: '/api/public/companion/finalize',
    path: '/api/public/companion/finalize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCompanionUploadRoute =
  ApiPublicCompanionUploadRouteImport.update({
    id: '/api/public/companion/upload',
    path: '/api/public/companion/upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCompanionUploadUrlRoute =
  ApiPublicCompanionUploadUrlRouteImport.update({
    id: '/api/public/companion/upload-url',
    path: '/api/public/companion/upload-url',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleDriveCallbackRoute =
  ApiPublicGoogleDriveCallbackRouteImport.update({
    id: '/api/public/google-drive/callback',
    path: '/api/public/google-drive/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/informasi': typeof InformasiRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/absen/$token': typeof AbsenTokenRoute
  '/detail/$key': typeof DetailKeyRoute
  '/event/$id': typeof EventIdRoute
  '/project/$id': typeof ProjectIdRoute
  '/admin/akses': typeof AuthenticatedAdminAksesRoute
  '/admin/approval': typeof AuthenticatedAdminApprovalRoute
  '/admin/atm': typeof AuthenticatedAdminAtmRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/drive': typeof AuthenticatedAdminDriveRoute
  '/admin/edc': typeof AuthenticatedAdminEdcRoute
  '/admin/foto': typeof AuthenticatedAdminFotoRoute
  '/admin/ip': typeof AuthenticatedAdminIpRoute
  '/admin/jabatan': typeof AuthenticatedAdminJabatanRoute
  '/admin/jenis-perangkat': typeof AuthenticatedAdminJenisPerangkatRoute
  '/admin/pegawai': typeof AuthenticatedAdminPegawaiRoute
  '/admin/perangkat': typeof AuthenticatedAdminPerangkatRoute
  '/admin/plugin': typeof AuthenticatedAdminPluginRoute
  '/admin/project': typeof AuthenticatedAdminProjectRoute
  '/admin/project-progress': typeof AuthenticatedAdminProjectProgressRoute
  '/admin/tiket': typeof AuthenticatedAdminTiketRoute
  '/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/admin/tutorial': typeof AuthenticatedAdminTutorialRoute
  '/admin/uker': typeof AuthenticatedAdminUkerRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/event/$id': typeof AuthenticatedAdminEventIdRoute
  '/api/public/companion/delete-event': typeof ApiPublicCompanionDeleteEventRoute
  '/api/public/companion/drive-status': typeof ApiPublicCompanionDriveStatusRoute
  '/api/public/companion/finalize': typeof ApiPublicCompanionFinalizeRoute
  '/api/public/companion/upload': typeof ApiPublicCompanionUploadRoute
  '/api/public/companion/upload-url': typeof ApiPublicCompanionUploadUrlRoute
  '/api/public/google-drive/callback': typeof ApiPublicGoogleDriveCallbackRoute
  '/admin/event/': typeof AuthenticatedAdminEventIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/informasi': typeof InformasiRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/absen/$token': typeof AbsenTokenRoute
  '/detail/$key': typeof DetailKeyRoute
  '/event/$id': typeof EventIdRoute
  '/project/$id': typeof ProjectIdRoute
  '/admin/akses': typeof AuthenticatedAdminAksesRoute
  '/admin/approval': typeof AuthenticatedAdminApprovalRoute
  '/admin/atm': typeof AuthenticatedAdminAtmRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/drive': typeof AuthenticatedAdminDriveRoute
  '/admin/edc': typeof AuthenticatedAdminEdcRoute
  '/admin/foto': typeof AuthenticatedAdminFotoRoute
  '/admin/ip': typeof AuthenticatedAdminIpRoute
  '/admin/jabatan': typeof AuthenticatedAdminJabatanRoute
  '/admin/jenis-perangkat': typeof AuthenticatedAdminJenisPerangkatRoute
  '/admin/pegawai': typeof AuthenticatedAdminPegawaiRoute
  '/admin/perangkat': typeof AuthenticatedAdminPerangkatRoute
  '/admin/plugin': typeof AuthenticatedAdminPluginRoute
  '/admin/project': typeof AuthenticatedAdminProjectRoute
  '/admin/project-progress': typeof AuthenticatedAdminProjectProgressRoute
  '/admin/tiket': typeof AuthenticatedAdminTiketRoute
  '/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/admin/tutorial': typeof AuthenticatedAdminTutorialRoute
  '/admin/uker': typeof AuthenticatedAdminUkerRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/event/$id': typeof AuthenticatedAdminEventIdRoute
  '/api/public/companion/delete-event': typeof ApiPublicCompanionDeleteEventRoute
  '/api/public/companion/drive-status': typeof ApiPublicCompanionDriveStatusRoute
  '/api/public/companion/finalize': typeof ApiPublicCompanionFinalizeRoute
  '/api/public/companion/upload': typeof ApiPublicCompanionUploadRoute
  '/api/public/companion/upload-url': typeof ApiPublicCompanionUploadUrlRoute
  '/api/public/google-drive/callback': typeof ApiPublicGoogleDriveCallbackRoute
  '/admin/event': typeof AuthenticatedAdminEventIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/informasi': typeof InformasiRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/absen/$token': typeof AbsenTokenRoute
  '/detail/$key': typeof DetailKeyRoute
  '/event/$id': typeof EventIdRoute
  '/project/$id': typeof ProjectIdRoute
  '/_authenticated/admin/akses': typeof AuthenticatedAdminAksesRoute
  '/_authenticated/admin/approval': typeof AuthenticatedAdminApprovalRoute
  '/_authenticated/admin/atm': typeof AuthenticatedAdminAtmRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/_authenticated/admin/drive': typeof AuthenticatedAdminDriveRoute
  '/_authenticated/admin/edc': typeof AuthenticatedAdminEdcRoute
  '/_authenticated/admin/foto': typeof AuthenticatedAdminFotoRoute
  '/_authenticated/admin/ip': typeof AuthenticatedAdminIpRoute
  '/_authenticated/admin/jabatan': typeof AuthenticatedAdminJabatanRoute
  '/_authenticated/admin/jenis-perangkat': typeof AuthenticatedAdminJenisPerangkatRoute
  '/_authenticated/admin/pegawai': typeof AuthenticatedAdminPegawaiRoute
  '/_authenticated/admin/perangkat': typeof AuthenticatedAdminPerangkatRoute
  '/_authenticated/admin/plugin': typeof AuthenticatedAdminPluginRoute
  '/_authenticated/admin/project': typeof AuthenticatedAdminProjectRoute
  '/_authenticated/admin/project-progress': typeof AuthenticatedAdminProjectProgressRoute
  '/_authenticated/admin/tiket': typeof AuthenticatedAdminTiketRoute
  '/_authenticated/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/_authenticated/admin/tutorial': typeof AuthenticatedAdminTutorialRoute
  '/_authenticated/admin/uker': typeof AuthenticatedAdminUkerRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/event/$id': typeof AuthenticatedAdminEventIdRoute
  '/api/public/companion/delete-event': typeof ApiPublicCompanionDeleteEventRoute
  '/api/public/companion/drive-status': typeof ApiPublicCompanionDriveStatusRoute
  '/api/public/companion/finalize': typeof ApiPublicCompanionFinalizeRoute
  '/api/public/companion/upload': typeof ApiPublicCompanionUploadRoute
  '/api/public/companion/upload-url': typeof ApiPublicCompanionUploadUrlRoute
  '/api/public/google-drive/callback': typeof ApiPublicGoogleDriveCallbackRoute
  '/_authenticated/admin/event/': typeof AuthenticatedAdminEventIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/informasi'
    | '/privacy-policy'
    | '/profil'
    | '/reset-password'
    | '/terms-of-service'
    | '/absen/$token'
    | '/detail/$key'
    | '/event/$id'
    | '/project/$id'
    | '/admin/akses'
    | '/admin/approval'
    | '/admin/atm'
    | '/admin/audit'
    | '/admin/crm'
    | '/admin/drive'
    | '/admin/edc'
    | '/admin/foto'
    | '/admin/ip'
    | '/admin/jabatan'
    | '/admin/jenis-perangkat'
    | '/admin/pegawai'
    | '/admin/perangkat'
    | '/admin/plugin'
    | '/admin/project'
    | '/admin/project-progress'
    | '/admin/tiket'
    | '/admin/tools'
    | '/admin/tutorial'
    | '/admin/uker'
    | '/admin/users'
    | '/admin/'
    | '/admin/event/$id'
    | '/api/public/companion/delete-event'
    | '/api/public/companion/drive-status'
    | '/api/public/companion/finalize'
    | '/api/public/companion/upload'
    | '/api/public/companion/upload-url'
    | '/api/public/google-drive/callback'
    | '/admin/event/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/informasi'
    | '/privacy-policy'
    | '/profil'
    | '/reset-password'
    | '/terms-of-service'
    | '/absen/$token'
    | '/detail/$key'
    | '/event/$id'
    | '/project/$id'
    | '/admin/akses'
    | '/admin/approval'
    | '/admin/atm'
    | '/admin/audit'
    | '/admin/crm'
    | '/admin/drive'
    | '/admin/edc'
    | '/admin/foto'
    | '/admin/ip'
    | '/admin/jabatan'
    | '/admin/jenis-perangkat'
    | '/admin/pegawai'
    | '/admin/perangkat'
    | '/admin/plugin'
    | '/admin/project'
    | '/admin/project-progress'
    | '/admin/tiket'
    | '/admin/tools'
    | '/admin/tutorial'
    | '/admin/uker'
    | '/admin/users'
    | '/admin'
    | '/admin/event/$id'
    | '/api/public/companion/delete-event'
    | '/api/public/companion/drive-status'
    | '/api/public/companion/finalize'
    | '/api/public/companion/upload'
    | '/api/public/companion/upload-url'
    | '/api/public/google-drive/callback'
    | '/admin/event'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/informasi'
    | '/privacy-policy'
    | '/profil'
    | '/reset-password'
    | '/terms-of-service'
    | '/absen/$token'
    | '/detail/$key'
    | '/event/$id'
    | '/project/$id'
    | '/_authenticated/admin/akses'
    | '/_authenticated/admin/approval'
    | '/_authenticated/admin/atm'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/crm'
    | '/_authenticated/admin/drive'
    | '/_authenticated/admin/edc'
    | '/_authenticated/admin/foto'
    | '/_authenticated/admin/ip'
    | '/_authenticated/admin/jabatan'
    | '/_authenticated/admin/jenis-perangkat'
    | '/_authenticated/admin/pegawai'
    | '/_authenticated/admin/perangkat'
    | '/_authenticated/admin/plugin'
    | '/_authenticated/admin/project'
    | '/_authenticated/admin/project-progress'
    | '/_authenticated/admin/tiket'
    | '/_authenticated/admin/tools'
    | '/_authenticated/admin/tutorial'
    | '/_authenticated/admin/uker'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/event/$id'
    | '/api/public/companion/delete-event'
    | '/api/public/companion/drive-status'
    | '/api/public/companion/finalize'
    | '/api/public/companion/upload'
    | '/api/public/companion/upload-url'
    | '/api/public/google-drive/callback'
    | '/_authenticated/admin/event/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InformasiRoute: typeof InformasiRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfilRoute: typeof ProfilRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AbsenTokenRoute: typeof AbsenTokenRoute
  DetailKeyRoute: typeof DetailKeyRoute
  EventIdRoute: typeof EventIdRoute
  ProjectIdRoute: typeof ProjectIdRoute
  ApiPublicCompanionDeleteEventRoute: typeof ApiPublicCompanionDeleteEventRoute
  ApiPublicCompanionDriveStatusRoute: typeof ApiPublicCompanionDriveStatusRoute
  ApiPublicCompanionFinalizeRoute: typeof ApiPublicCompanionFinalizeRoute
  ApiPublicCompanionUploadRoute: typeof ApiPublicCompanionUploadRoute
  ApiPublicCompanionUploadUrlRoute: typeof ApiPublicCompanionUploadUrlRoute
  ApiPublicGoogleDriveCallbackRoute: typeof ApiPublicGoogleDriveCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi': {
      id: '/informasi'
      path: '/informasi'
      fullPath: '/informasi'
      preLoaderRoute: typeof InformasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/absen/$token': {
      id: '/absen/$token'
      path: '/absen/$token'
      fullPath: '/absen/$token'
      preLoaderRoute: typeof AbsenTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail/$key': {
      id: '/detail/$key'
      path: '/detail/$key'
      fullPath: '/detail/$key'
      preLoaderRoute: typeof DetailKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/akses': {
      id: '/_authenticated/admin/akses'
      path: '/admin/akses'
      fullPath: '/admin/akses'
      preLoaderRoute: typeof AuthenticatedAdminAksesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/approval': {
      id: '/_authenticated/admin/approval'
      path: '/admin/approval'
      fullPath: '/admin/approval'
      preLoaderRoute: typeof AuthenticatedAdminApprovalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/atm': {
      id: '/_authenticated/admin/atm'
      path: '/admin/atm'
      fullPath: '/admin/atm'
      preLoaderRoute: typeof AuthenticatedAdminAtmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/crm': {
      id: '/_authenticated/admin/crm'
      path: '/admin/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AuthenticatedAdminCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/drive': {
      id: '/_authenticated/admin/drive'
      path: '/admin/drive'
      fullPath: '/admin/drive'
      preLoaderRoute: typeof AuthenticatedAdminDriveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/edc': {
      id: '/_authenticated/admin/edc'
      path: '/admin/edc'
      fullPath: '/admin/edc'
      preLoaderRoute: typeof AuthenticatedAdminEdcRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/foto': {
      id: '/_authenticated/admin/foto'
      path: '/admin/foto'
      fullPath: '/admin/foto'
      preLoaderRoute: typeof AuthenticatedAdminFotoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ip': {
      id: '/_authenticated/admin/ip'
      path: '/admin/ip'
      fullPath: '/admin/ip'
      preLoaderRoute: typeof AuthenticatedAdminIpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/jabatan': {
      id: '/_authenticated/admin/jabatan'
      path: '/admin/jabatan'
      fullPath: '/admin/jabatan'
      preLoaderRoute: typeof AuthenticatedAdminJabatanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/jenis-perangkat': {
      id: '/_authenticated/admin/jenis-perangkat'
      path: '/admin/jenis-perangkat'
      fullPath: '/admin/jenis-perangkat'
      preLoaderRoute: typeof AuthenticatedAdminJenisPerangkatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pegawai': {
      id: '/_authenticated/admin/pegawai'
      path: '/admin/pegawai'
      fullPath: '/admin/pegawai'
      preLoaderRoute: typeof AuthenticatedAdminPegawaiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/perangkat': {
      id: '/_authenticated/admin/perangkat'
      path: '/admin/perangkat'
      fullPath: '/admin/perangkat'
      preLoaderRoute: typeof AuthenticatedAdminPerangkatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/plugin': {
      id: '/_authenticated/admin/plugin'
      path: '/admin/plugin'
      fullPath: '/admin/plugin'
      preLoaderRoute: typeof AuthenticatedAdminPluginRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/project': {
      id: '/_authenticated/admin/project'
      path: '/admin/project'
      fullPath: '/admin/project'
      preLoaderRoute: typeof AuthenticatedAdminProjectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/project-progress': {
      id: '/_authenticated/admin/project-progress'
      path: '/admin/project-progress'
      fullPath: '/admin/project-progress'
      preLoaderRoute: typeof AuthenticatedAdminProjectProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tiket': {
      id: '/_authenticated/admin/tiket'
      path: '/admin/tiket'
      fullPath: '/admin/tiket'
      preLoaderRoute: typeof AuthenticatedAdminTiketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tools': {
      id: '/_authenticated/admin/tools'
      path: '/admin/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AuthenticatedAdminToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tutorial': {
      id: '/_authenticated/admin/tutorial'
      path: '/admin/tutorial'
      fullPath: '/admin/tutorial'
      preLoaderRoute: typeof AuthenticatedAdminTutorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/uker': {
      id: '/_authenticated/admin/uker'
      path: '/admin/uker'
      fullPath: '/admin/uker'
      preLoaderRoute: typeof AuthenticatedAdminUkerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/event/': {
      id: '/_authenticated/admin/event/'
      path: '/admin/event'
      fullPath: '/admin/event/'
      preLoaderRoute: typeof AuthenticatedAdminEventIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/event/$id': {
      id: '/_authenticated/admin/event/$id'
      path: '/admin/event/$id'
      fullPath: '/admin/event/$id'
      preLoaderRoute: typeof AuthenticatedAdminEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/companion/delete-event': {
      id: '/api/public/companion/delete-event'
      path: '/api/public/companion/delete-event'
      fullPath: '/api/public/companion/delete-event'
      preLoaderRoute: typeof ApiPublicCompanionDeleteEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/companion/drive-status': {
      id: '/api/public/companion/drive-status'
      path: '/api/public/companion/drive-status'
      fullPath: '/api/public/companion/drive-status'
      preLoaderRoute: typeof ApiPublicCompanionDriveStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/companion/finalize': {
      id: '/api/public/companion/finalize'
      path: '/api/public/companion/finalize'
      fullPath: '/api/public/companion/finalize'
      preLoaderRoute: typeof ApiPublicCompanionFinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/companion/upload': {
      id: '/api/public/companion/upload'
      path: '/api/public/companion/upload'
      fullPath: '/api/public/companion/upload'
      preLoaderRoute: typeof ApiPublicCompanionUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/companion/upload-url': {
      id: '/api/public/companion/upload-url'
      path: '/api/public/companion/upload-url'
      fullPath: '/api/public/companion/upload-url'
      preLoaderRoute: typeof ApiPublicCompanionUploadUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-drive/callback': {
      id: '/api/public/google-drive/callback'
      path: '/api/public/google-drive/callback'
      fullPath: '/api/public/google-drive/callback'
      preLoaderRoute: typeof ApiPublicGoogleDriveCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAksesRoute: typeof AuthenticatedAdminAksesRoute
  AuthenticatedAdminApprovalRoute: typeof AuthenticatedAdminApprovalRoute
  AuthenticatedAdminAtmRoute: typeof AuthenticatedAdminAtmRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCrmRoute: typeof AuthenticatedAdminCrmRoute
  AuthenticatedAdminDriveRoute: typeof AuthenticatedAdminDriveRoute
  AuthenticatedAdminEdcRoute: typeof AuthenticatedAdminEdcRoute
  AuthenticatedAdminFotoRoute: typeof AuthenticatedAdminFotoRoute
  AuthenticatedAdminIpRoute: typeof AuthenticatedAdminIpRoute
  AuthenticatedAdminJabatanRoute: typeof AuthenticatedAdminJabatanRoute
  AuthenticatedAdminJenisPerangkatRoute: typeof AuthenticatedAdminJenisPerangkatRoute
  AuthenticatedAdminPegawaiRoute: typeof AuthenticatedAdminPegawaiRoute
  AuthenticatedAdminPerangkatRoute: typeof AuthenticatedAdminPerangkatRoute
  AuthenticatedAdminPluginRoute: typeof AuthenticatedAdminPluginRoute
  AuthenticatedAdminProjectRoute: typeof AuthenticatedAdminProjectRoute
  AuthenticatedAdminProjectProgressRoute: typeof AuthenticatedAdminProjectProgressRoute
  AuthenticatedAdminTiketRoute: typeof AuthenticatedAdminTiketRoute
  AuthenticatedAdminToolsRoute: typeof AuthenticatedAdminToolsRoute
  AuthenticatedAdminTutorialRoute: typeof AuthenticatedAdminTutorialRoute
  AuthenticatedAdminUkerRoute: typeof AuthenticatedAdminUkerRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEventIdRoute: typeof AuthenticatedAdminEventIdRoute
  AuthenticatedAdminEventIndexRoute: typeof AuthenticatedAdminEventIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAksesRoute: AuthenticatedAdminAksesRoute,
  AuthenticatedAdminApprovalRoute: AuthenticatedAdminApprovalRoute,
  AuthenticatedAdminAtmRoute: AuthenticatedAdminAtmRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminCrmRoute: AuthenticatedAdminCrmRoute,
  AuthenticatedAdminDriveRoute: AuthenticatedAdminDriveRoute,
  AuthenticatedAdminEdcRoute: AuthenticatedAdminEdcRoute,
  AuthenticatedAdminFotoRoute: AuthenticatedAdminFotoRoute,
  AuthenticatedAdminIpRoute: AuthenticatedAdminIpRoute,
  AuthenticatedAdminJabatanRoute: AuthenticatedAdminJabatanRoute,
  AuthenticatedAdminJenisPerangkatRoute: AuthenticatedAdminJenisPerangkatRoute,
  AuthenticatedAdminPegawaiRoute: AuthenticatedAdminPegawaiRoute,
  AuthenticatedAdminPerangkatRoute: AuthenticatedAdminPerangkatRoute,
  AuthenticatedAdminPluginRoute: AuthenticatedAdminPluginRoute,
  AuthenticatedAdminProjectRoute: AuthenticatedAdminProjectRoute,
  AuthenticatedAdminProjectProgressRoute:
    AuthenticatedAdminProjectProgressRoute,
  AuthenticatedAdminTiketRoute: AuthenticatedAdminTiketRoute,
  AuthenticatedAdminToolsRoute: AuthenticatedAdminToolsRoute,
  AuthenticatedAdminTutorialRoute: AuthenticatedAdminTutorialRoute,
  AuthenticatedAdminUkerRoute: AuthenticatedAdminUkerRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminEventIdRoute: AuthenticatedAdminEventIdRoute,
  AuthenticatedAdminEventIndexRoute: AuthenticatedAdminEventIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InformasiRoute: InformasiRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfilRoute: ProfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AbsenTokenRoute: AbsenTokenRoute,
  DetailKeyRoute: DetailKeyRoute,
  EventIdRoute: EventIdRoute,
  ProjectIdRoute: ProjectIdRoute,
  ApiPublicCompanionDeleteEventRoute: ApiPublicCompanionDeleteEventRoute,
  ApiPublicCompanionDriveStatusRoute: ApiPublicCompanionDriveStatusRoute,
  ApiPublicCompanionFinalizeRoute: ApiPublicCompanionFinalizeRoute,
  ApiPublicCompanionUploadRoute: ApiPublicCompanionUploadRoute,
  ApiPublicCompanionUploadUrlRoute: ApiPublicCompanionUploadUrlRoute,
  ApiPublicGoogleDriveCallbackRoute: ApiPublicGoogleDriveCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
